### ISSUE TITLE
Speed limitation?

### ISSUE THREAD

**Issue by chaminaud** [borzunov/bit-torrent#2]
In my test case I have 1 seeder and one leecher, and it is stuck at 380KB/s

**update**
find solution,  I change the  DOWNLOAD_REQUEST_QUEUE_SIZE in peer_manager.py

**Comment by borzunov** [comment]
I've increased the default queue size in f5abd73a563fb551be0c20c48c5b8e6a60883bfe. Thank you for pointing this out!
