### ISSUE TITLE
Is supported relative paths?

### ISSUE THREAD

**Issue by latot** [borzunov/bit-torrent#4]
Hi!, i have a qustion, well the title, a have torrents in a external hdd, and i seed them, but it change the absolute path when i reconnect it, so, the project supports relative path? (ex. ```./torrents/fuuu```)

Thx.

**Comment by borzunov** [comment]
Hi @latot!

The CLI version supports relative paths by default (you can use `--download-dir` option). The GUI version does not support them by default, but you can change [this line](https://github.com/borzunov/bit-torrent/blob/5d8b9f01cc9139ec071ef7115724fb6dfa4b10c6/torrent_gui.py#L96) to hardcode such a path:
```python
self._download_dir = './torrents/fuuu'
```
