### ISSUE TITLE
2 bugs.

### ISSUE THREAD

**Issue by kingctan** [borzunov/bit-torrent#5]
1,  .torrent file search from dht has no announce, this torrent added failed with exception.
2, no torrent task, run status will exit with exception.

**Comment by borzunov** [comment]
Hi @kingctan!

1. This client doesn't support DHT.
2. I confirm there is a problem, I'll fix it later.

**Comment by kingctan** [comment]
@borzunov thanks for reply.

any idea to support dht, I need this feature.

Thanks.

**Comment by borzunov** [comment]
I don't plan to implement DHT for now.

**Comment by kingctan** [comment]
@borzunov 
OK. 
I am thinking of adding this feature, but no idea recently. ^_^

Thanks.

**Comment by borzunov** [comment]
The second bug has been fixed in ace0f3ac5e7e3d0aa50a467ca0f6a74a00d9b044.

**Comment by milahu** [comment]
> 1\. This client doesn't support DHT

early DHT draft in the fork [github.com/beyondcoast/bit-torrent](https://github.com/beyondcoast/bit-torrent)
